services:
  vote-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vote-api:latest
    ports:
      - "8080:8080"
    environment:
      PG_URL: ${PG_URL}

volumes:
  postgres_data:
