networks:
  vote-network:
    driver: bridge

services:
  vote-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vote-api:latest
    ports:
      - "8080:8080"
    environment:
      PG_URL: ${PG_URL}
    depends_on:
      - db
    networks:
      - vote-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: vote
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vote-network

volumes:
  postgres_data: