services:
  vote-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vote-api:latest
    ports:
      - "8080:8080"
    environment:
      PG_URL: ${PG_URL}
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      PG_URL: ${PG_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: