services:
  vote-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vote-api:latest
    ports:
      - "8080:8080"
    environment:
      PG_URL: ${{ secrets.PG_URL }}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vote_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
