name: Deploy Client Application

on:
  push:
    branches:
      - feature/dockerfile  # Déclenche le workflow sur les push vers cette branche

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies for Client
        working-directory: ./client
        run: yarn install
      - name: Build Client Application
        working-directory: ./client
        run: yarn build
      - name: Dockerize Client
        run: |
          docker build -f client/Dockerfile -t client-app .
      - name: Deploy Client (Example with Docker)
        run: |
          docker tag client-app:latest ${{ secrets.DOCKER_USERNAME }}/client-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/client-app:latest
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/client-app:latest
