name: Deploy vote-api

on:
  push:
    branches:
      - feature/dockerfile  # Déclenche le workflow sur les push vers cette branche

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push vote-api
        run: |
          docker-compose -f vote-api/docker-compose.yml build vote-api
          docker tag vote-api:latest ${{ secrets.DOCKER_USERNAME }}/vote-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vote-api:latest
        env:
          PG_URL: ${{ secrets.PG_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy vote-api
        run: |
          docker-compose -f vote-api/docker-compose.yml up -d
        env:
          PG_URL: ${{ secrets.PG_URL }}
