name: Deploy Client Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies for Client
        working-directory: ./web-client
        run: yarn install

      - name: Build Client Application
        working-directory: ./web-client
        run: yarn build

      - name: Dockerize Client
        working-directory: ./web-client
        run: |
          docker build -f Dockerfile -t client-app .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to DockerHub
        run: |
          docker tag client-app:latest ${{ secrets.DOCKER_USERNAME }}/client-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/client-app:latest

      - name: Deploy Client (Run Docker Container)
        run: |
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/client-app:latest
